### PR TITLE
UI: add FAB to create a new batch

### PR DESCRIPTION
**Pull request by panwarab**
> added a FAB , yet to add DB Functionality

FAB will be used to add a new course. For now, it just displays Toast.

> need to update color scheme fully

### CODE REVIEW

**Comment by piyush0** [comment]
As this is a UI based PR, I'd like to see a screenshot before merging. Kudos on getting started. :)

**Comment by panwarab** [comment]
Here it is :- 
device-2017-04-17-184139

**Comment by panwarab** [comment]
Sorry, missed out preview before sending it. And colors are odd for now, will cover it in next one. Apart from this, I have a few queries regarding backend? Should we continue this on gitter?

**Comment by piyush0** [comment]
Its okay. Colors are not final as of yet anyway.
As far as backend is concerned, we'll integrate it with accounts.codingblocks.com when it is ready. Until then we can start working on the features mentioned by @championswimmer in issue #1

**Pull request merged**
